### ISSUE TITLE
New Microsoft Teams application

### ISSUE THREAD

**Issue by DrFate09** [RobertD502/TeamsStatusMacOS#1]
Does this integration also work with the new Microsoft Teams application?

**Comment by RobertD502** [comment]
Please post the version of your Microsoft Teams MacOS app.

Edit: disregard. It doesn't. I'll need to look at the log to see what is logged when in a meeting.

**Comment by RobertD502** [comment]
Just looked and it seems that the same log file is still there. However, the log file is not being updated which I suspect is a bug on the Teams end. Will update once I figure out if a new location is being used or if they fix what I suspect is a bug on their end.

**Comment by Goobaroo** [comment]
I found some dated logs in `~/Library/Group Containers/UBF8T346G9.com.microsoft.teams/Library/Application Support/Logs` but they do not match the events you were tracking before.

**Comment by RobertD502** [comment]
I did see those and had the same findings. Will have to figure out how these logs correspond to state within Teams (that's if those logs are the ones that should be used).

**Comment by RobertD502** [comment]
@DrFate09 @Goobaroo 

I have figured out a workaround that doesn't involve any Teams logs. Sniffing around my Mac's logs, I was able to identify that Teams invokes/tells the Mac's power management to prevent the display from going to sleep when a meeting is joined: there is a clear event logged for the `powerd` process when a Teams meeting is joined and when it is exited.

I have rewritten the scripts to allow users of the new Teams application to be able to fetch their meeting state - I will be pushing the changes out shortly (version 0.2).

Once the changes are live, if you've already followed the installation steps prior to this change:
1. Unload the current script with either:

```shell
launchctl unload -w ~/Library/LaunchAgents/com.homeassistant.MSTeamsStatusSender-Local.plist
```

or

```shell
launchctl unload -w ~/Library/LaunchAgents/com.homeassistant.MSTeamsStatusSender-External.plist
```
2. Download the new bash script that corresponds to your setup (either local or external) and move it in your `Teams_Status` folder, replacing the old bash script.
3. Edit the new script with your information. `Important:` There is a new variable titled `teams_version`. Be sure to set this variable to `"New"` so the script knows to use the method related to the new MS Teams version.
4. Make the new script executable with either:

```shell
chmod +x ~/Documents/Teams_Status/ms-teams-status-local.sh
```

or

```shell
chmod +x ~/Documents/Teams_Status/ms-teams-status-external.sh
```
5. Remove the quarantine attribute with either:

```shell
xattr -d com.apple.quarantine ~/Documents/Teams_Status/ms-teams-status-local.sh
```

or

```shell
xattr -d com.apple.quarantine ~/Documents/Teams_Status/ms-teams-status-external.sh
```

6. Finally, load the script with either:

```shell
launchctl load -w ~/Library/LaunchAgents/com.homeassistant.MSTeamsStatusSender-Local.plist
```

or

```shell
launchctl load -w ~/Library/LaunchAgents/com.homeassistant.MSTeamsStatusSender-External.plist
```

After all of that is done, you may need to log out/ log back in or restart your Mac for the script to start automatically running every 2 seconds.

**Comment by RobertD502** [comment]
Support added in #2
